### ISSUE TITLE
STORY - Create splash screen

### ISSUE THREAD

**Issue by yasgreen93** [JOYERLtd/joyerapp#10]
@OlliePorter to upload image of the splash screen

Splash Screen:
<img src="https://user-images.githubusercontent.com/13727615/44300007-bd383780-a2f7-11e8-9e14-dbf147593e5f.png" data-canonical-src="https://user-images.githubusercontent.com/13727615/44300007-bd383780-a2f7-11e8-9e14-dbf147593e5f.png" width="200" />

**Comment by OlliePorter** [comment]
@yasgreen93 splash screen added.
